name: Build
on:
  push:
    branches: [ master, Rushil ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build with Gradle
        run: ./gradlew build

      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          script: ./gradlew connectedCheck
      
  test:
    runs-on: macos-latest
    needs: build
    strategy:
      matrix:
        api-level: [23, 34, 25, 26, 27, 28, 29]
        target: [default]
      
      
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Checkout the code
        uses: actions/checkout@v2

