name: Build
on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build with Gradle
        run: ./gradlew build
      
  test:
    runs-on: macos-latest
    needs: build
    strategy:
      matrix:
        api-level: [21, 23, 29]
        target: [default]
      
      
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.3.4

