name: Build
on:
  pull_request:
    branches: [ Rushil ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build with Gradle
        run: ./gradlew build
